export default [
  'awsm',
  'en kilde til umåtelig visdom',
  'deilig',
  'herlig',
  'fantastisk',
  'nydelig',
  'en blomstrende inspirasjon',
  'som fersk sjokolade',
  'som et saftig jorbær',
  'et forbilde',
  'aller best',
  'innbydende',
  'som en heftig dans',
  'som en grasiøs rose',
  'velduftende',
  'superduper diddelidam',
  'en silkemyk sang',
  'et knasende eple',
  'en lekkerbisken',
  'alt jeg ønsker meg',
  'tipp, topp, tommel opp',
  'en glitrende diamant',
  'et romantisk stearinlys',
  'som et lett kyss på kinnet',
  'som en nybadet harepus',
  'helt uten sidestykke',
  'ustoppelig',
  'som en frisk vårmorgen',
  'som en lang sommernatt',
  'som den finaste eg veit',
  'som en uventet tusenlapp i jakkelomma',
  'som et blikkstille skogstjern',
  'som en sakte eksplosjon av ren lykke',
  'alt som betyr noe',
  'som et friskt pust',
  'som en velplassert knuseklem',
  'knusekoselig',
  'som en nyoppredd seng',
  'en nyåpnet eske kremtopper',
  'wooop wooop wooop woohooo',
  'som en bolle duggfrisk frukt'
]
