export default [
  'awsm',
  'en kilde til umåtelig visdom',
  'deilig',
  'herlig',
  'fantastisk',
  'nydelig',
  'en blomstrende inspirasjon',
  'som fersk sjokolade',
  'som et saftig jorbær',
  'et forbilde',
  'aller best',
  'innbydende',
  'som en heftig dans',
  'som en grasiøs rose',
  'velduftende',
  'superduper diddelidam',
  'en silkemyk sang',
  'et knasende eple',
  'en lekkerbisken',
  'alt jeg ønsker meg',
  'tipp, topp, tommel opp',
  'en glitrende diamant',
  'et romantisk stearinlys'
]
