on:
  release:
    types: [published]
    branches: [master]
name: Test and Deploy on release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm test
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      run: now --prod --token ${ZEIT_TOKEN}
